### ISSUE TITLE
Add commits graph

### ISSUE THREAD

**Issue by milke** [milke/GitFinder-Issues#1]
GitFinder currently shows only chronologically ordered commits for a branch/tag/history, without any graphical representation. Add commit graph node to the left of other commit info in the list of commits.

**Comment by luxlogica** [comment]
This is a really important feature, specially when dealing with newbies. Right now I'm trying to teach our workflow to new developers, which involves using *rebase* as well as *merge*, in order to try to keep the repository history as linear as possible. 
Trying to teach this without a commit graph is basically impossible...

**Comment by milke** [comment]
@luxlogica, if you read [this](https://gitfinder.com/blog/why-gitfinder/34) blog post explaining the reasons for creating GitFinder, you'll understand better it first got features I needed the most. Since I almost exclusively worked with repositories with fairly simple structure and history, I never really needed commits graph. However, I understand it's a very desired feature and most other git GUI clients have it ([GitHub Desktop](https://desktop.github.com) being one of notable exceptions). As a matter of fact, I started needing it more too, so I've already working on it!

The graph algorithm and logic is already in place, I just need to make it draw nicely. It will appear in version **1.4**. However, I'd like to squeeze some other important features (like, per line stage/unstage/discard and revision/commit file tree) into that version and I expect it to be ready for release it 2 - 3 months. I'm not working full time on this project for a few reasons, hence I need some time.

**Comment by milke** [comment]
Hi @luxlogica, I hope you still use GitFinder and follow this and if that's the case, please be informed I just uploaded the latest beta of GitFinder (version **1.4b1**, build **65**), which sports brand new, straignt-lined, 10-colours commit graph added to the list of commits. You may want to give it a try and if you do, please let me know what you think and if it works well.

This latest beta also sports many other improvements and additions, the biggest being the ability to select multiple references in the sidebar and commits/files in the commits/files lists and to execute applicable contextual operations on such selection.

**Comment by milke** [comment]
Commit graph is implemented as of version **1.4**.
