### ISSUE TITLE
Multiple GitHub accounts with the same username

### ISSUE THREAD

**Issue by ajc** [milke/GitFinder-Issues#101]
Thanks so much for adding support for privately-hosted GitHub instances!

I seem to have a minor problem in that my username on our GitHub Enterprise instance at work happens to be the same as my GitHub.com username - this means I can't configure both work's GHE and github.com at once in GitFinder - confguring the second one ends up replacing the first one.

I realise this is a bit of an edge case, but perhaps it'd be nice to be able to rename the profiles in GitFinder to avoid the clashes or something like that? There's no rush.

Cheers,
 Cos.

**Comment by milke** [comment]
@ajc, since this has been resolved and available for quite some time now, I'm closing this one.
