### ISSUE TITLE
Cannot use gitconfig include directive with symlinks

### ISSUE THREAD

**Issue by tosie** [milke/GitFinder-Issues#109]
I am using the include directive in my .gitconfig to have different sets of config options for different types of machines like this:

```
[includeIf "gitdir/i:/Users/"]
  path = .gitconfig-macos

[includeIf "gitdir/i:C:/"]
  path = .gitconfig-windows

[includeIf "gitdir/i:/"]
  path = .gitconfig-linux

[include]
  path = .gitconfig.local
```

Some of the included files are symlinked like this:

```
.gitconfig         -> $HOME/.dotfiles/git/gitconfig.symlink
.gitconfig-linux   -> $HOME/.dotfiles/git/gitconfig-linux.symlink
.gitconfig-macos   -> $HOME/.dotfiles/git/gitconfig-macos.symlink
.gitconfig-windows -> $HOME/.dotfiles/git/gitconfig-windows.symlink
.gitconfig.local
```

When starting GitFinder, this message is shown:

<img width="372" alt="screenshot1" src="https://user-images.githubusercontent.com/20296/142388047-eaf0528e-b592-4872-a4d1-586e64f41e2f.png">

The includes settings look like this:

<img width="515" alt="screenshot2" src="https://user-images.githubusercontent.com/20296/142388118-2f1883d5-66ea-499a-bf3b-c5075f9f36f3.png">

Now when trying to match a file by selecting the symlink -- which is the only correct file path that matches the include directive -- this error message is shown:

<img width="912" alt="screenshot3" src="https://user-images.githubusercontent.com/20296/142388255-b9807b58-0b76-40b5-a9da-8d888bfd53c5.png">

Is there any way to use symlinked .gitconfig-includes?

**Comment by milke** [comment]
@tosie, we can call it a bug, I haven't predicted the case of included files being symlinks to other files.

Anyway, I've fixed it(I believe) in the latest beta build, which I've just uploaded. It's version **1.7.5b1 (build 119)** and you can download it directly [**here**](https://get.gitfinder.com/GitFinder_beta.dmg), but you can also update your current copy to it automatically, just select **Beta** update channel in the preferences, like in the picture below:
<img width="495" alt="Screen Shot 2021-11-18 at 20 02 09" src="https://user-images.githubusercontent.com/291305/142479888-770a8298-3614-41ab-ae87-8a9f76d490aa.png">
This version should handle included symlinks correctly, but just be aware that, when reporting included files, GitFinder will not report symlinks defined in config file(s), it will report symlinked targets instead, like for example in the pictures below:
<img width="372" alt="Screen Shot 2021-11-18 at 18 43 09" src="https://user-images.githubusercontent.com/291305/142480125-966eb70a-4897-4838-97ac-6cef8e3fbff2.png">
<img width="612" alt="Screen Shot 2021-11-18 at 18 43 19" src="https://user-images.githubusercontent.com/291305/142480130-88c54041-e235-497b-b977-f17388826b63.png">
You probably realise selecting included files is necessary to include them in GitFinder sandbox environment (GitFinder is fully sandboxed application).

Please try this beta build and let me know if it solves your problem.

**Comment by milke** [comment]
@tosie, any luck with the latest beta?

**Comment by tosie** [comment]
I am so sorry ... just today I came back to my mac and what can I say: It works fine. Thank you very much for the quick update!
