### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by 3rdcycle** [milke/GitFinder-Issues#112]
Just a small typo in the Menu Preferences Dialog "Defautls" -> "Defaults"
![Screenshot 2022-02-21 at 10 56 39](https://user-images.githubusercontent.com/1217821/154932538-f8ed2f3e-c4c7-4f13-bdaf-084b074fd4f7.png)

**Comment by milke** [comment]
@3rdcycle, thanks for catching this! It will be fixed in the next (beta) update.

**Comment by milke** [comment]
This is implemented in the latest beta version **1.7.5b2 (build 120)**. You can download the lates beta [**here**](https://get.gitfinder.com/GitFinder_beta.dmg), but you can also update your current copy using in-app updater. Just make sure to check for the **Beta** release channel in the update preferences.
