### ISSUE TITLE
404 error when trying to add Bitbucket repositories

### ISSUE THREAD

**Issue by ghost** [milke/GitFinder-Issues#115]
After adding a new Bitbucket account in the _Hosting_ tab of the GitFinder _Preferences_, the following error occurs:

```
not found (HTTP status code 404)

This endpoint has been removed. See our documentation for more information. https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-teams-get
```

See also the attached screenshot.

I didn't use GiFinder in a while, so I don't know since when this happens. But I recall I worked successfully with Bitbucket repos in the past.

<img width="260" alt="Screenshot 2022-06-11 at 15 51 54" src="https://user-images.githubusercontent.com/11961911/173190988-1859841a-f74d-480a-ab42-bb2fd449f6c6.png">

**Comment by heikomannherz** [comment]
Thank you! This seems to work so far in **1.7.6b1**. However, I realised once I was able to access the repositories this way, the next time I open the corresponding section in the Preferences it doesn't load the repositories any more. The spinner just keeps spinning while retrieving repositories. 


<img width="687" alt="Snipaste_2022-07-14_08-31-20" src="https://user-images.githubusercontent.com/11961911/178916394-24206f7c-5b1f-45e4-a857-a2d49585484b.png">

**Comment by milke** [comment]
What happens if you select any of those "subaccounts" (children of your main account you selected), do you see any repository in there? Currently there's a bug that if you don't have a single repository under an account, GitFinder keeps spinning that "_Fetching repositories…_", instead of showing an empty list. I've already fixed that and it will go in another beta, or even the official **1.7.6** in a few days.

**Comment by heikomannherz** [comment]
The same, unfortunately ...

<img width="691" alt="image" src="https://user-images.githubusercontent.com/11961911/178941882-f46f3cee-4c92-4f97-893c-1cf9881b01f9.png">

**Comment by milke** [comment]
Right, I forgot to update API endpoint for refreshed token request. Additionally, there's another bug in creating error message for that case, which throws exception between GitFinder application and host communication XPC service, hence the response from the XPC service never reaches the application so it "thinks" host is still fetching repositories.

I'll update another beta fixing this today, thanks for reporting.

**Comment by milke** [comment]
Okay, I've uploaded a new beta, version **1.7.6b1 (build 122)**, download directly [**here**](https://gitfinder.com/updates/GitFinder_beta.dmg), or update from within the application, using **Beta release channel**.

It fixes both issues I mentioned above (apart from some other fixes a well). Try it out on your Bitbucket account and let me know how it goes.

**Comment by heikomannherz** [comment]
Looks good now! Thanks a million.

**Comment by heikomannherz** [comment]
At least that's what I thought a couple of minutes ago. While the application was running in the background, the following error message popped up:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/11961911/179162457-7868dcb9-b5e9-4d23-b219-59c9580db7a8.png">

Dunno if that is related, though.
