### ISSUE TITLE
Application window won't appear

### ISSUE THREAD

**Issue by josefguenther** [milke/GitFinder-Issues#119]
Hi, I selected no menu icon and I believe there was an option for no dock icon and I unselected that. Now GitFinder won't open. When I kill in in Activity Monitor and try again, the process does appear but there's no window. I can't access the preferences!

**Comment by milke** [comment]
Yeah, that's a bit unfortunate combination. Perhaps I should somehow prevent it from happening. Anyway, here's how you can fix it:

**Method 1**
* Launch GitFinder (but you won't see any hints of it running, unless you look it up in the Activity Monitor)
* Browse to some repository (monitored by GitFinder) in Finder, you should see git status icon badges
* From the contextual menu invoke any GitFinder window, for example _"Browser"_ for repository browser. That will put GitFinder application in front, showing its active window, but the Dock (and hence the main menu) won't be visible
* Even though the main menu isn't visible, you can still invoke its commands with keyboard shortcuts. Press **command + ,** (or whatever shortcut you set for the **Preferences…** menu item if you changed defaults) and that will invoke the preferences window. Change your settings in there.

**Method 2** (faster but requires kicking off Terminal)
* Quit GitFinder
* Open the Terminal and execute this line
```defaults delete ag.zigz.GitFinder GFMenuBarIconShown```
* Launch GitFinder. The status menu bar icon will be shown again and you can use it to access the preferences.
