### ISSUE TITLE
GitFinder is running, but I don't see icon badges 

### ISSUE THREAD

**Issue by asegner** [milke/GitFinder-Issues#120]
I am on macOS Ventura and GitFinder Version 1.7.8 (129) is running, but I don't see icon badges. 

- I have uninstalled and reinstalled. 
- I do see git menu commands in the right click menu. 
- I do see GitFinderSync processes in Activity Monitor however...
- I do not see an entry for GitFinderSync listed in Finder extensions for me to enable.

**Comment by asegner** [comment]
<img width="470" alt="Screenshot 2023-07-19 at 6 21 50 PM" src="https://github.com/milke/GitFinder-Issues/assets/5124661/2b172675-0b98-4cdd-a017-e53c40bb3fd0">
<img width="501" alt="Screenshot 2023-07-19 at 6 21 42 PM" src="https://github.com/milke/GitFinder-Issues/assets/5124661/6ec0fc31-6f01-4c70-b0dd-bd32601cf817">

**Comment by milke** [comment]
What extensions (apart from GitFinder) do you have in **"Added extensions"**?

<img width="481" alt="Screenshot 2023-07-20 at 00 31 41" src="https://github.com/milke/GitFinder-Issues/assets/291305/1cd38ef8-a674-4e05-bffa-b678fe565f90">

Besides GitFinder, do you have any other with checkmark **"Finder extensions"** checked?

<img width="440" alt="Screenshot 2023-07-20 at 00 31 58" src="https://github.com/milke/GitFinder-Issues/assets/291305/98e0b241-47c9-429c-9ca2-5e8503d01154">

**Comment by asegner** [comment]
Looks like i have a few:
<img width="437" alt="Screenshot 2023-07-19 at 6 36 18 PM" src="https://github.com/milke/GitFinder-Issues/assets/5124661/8705e4c6-9a96-4657-a910-3304d94a4e22">
<img width="443" alt="Screenshot 2023-07-19 at 6 36 24 PM" src="https://github.com/milke/GitFinder-Issues/assets/5124661/20faae4a-61f9-45d9-a970-4f8f28e14e03">
<img width="448" alt="Screenshot 2023-07-19 at 6 36 30 PM" src="https://github.com/milke/GitFinder-Issues/assets/5124661/f27b6248-5412-4994-b814-ac14a80f70a4">

**Comment by asegner** [comment]
That pointed me in the right direction - disabling MacZip Finder extension allowed the icon badges to appear again. Looks like these two extensions do not work well together.

**Comment by milke** [comment]
It's not about those two particular extensions, it's about FInderSync extensions in general. If two (or more) FinderSync extensions monitor the same folder(s), they collide over which one would present its own icon badges. And that happens even if some extension doesn't even provide any badges (like MacZip in this case). The extension which wins over is the one started first after login. But FinderSync extensions are started by the OS and that process is, as far as I know, uncontrolled and the order of extension started is unpredicted.

The trick here is to go over all FinderSync extensions in System Preferences and uncheck all, but the one you want to show its icon badges (GitFinder in this case). Once the desired extension takes over badge presentation, you can check back the others. So, all FinderSync extensions can function at the same time and present their contextual menu items/commands, but only one can present icon badges, which is logical. What is not logical is that Apple hasn't provided a way to prioritize which extension will show its icon badges. I filed a but report long time ago (at the time macOS 10.11 Ed Capitan was still the latest version), and nothing happened in the meanwhile.

This is all explained on the [support](https://gitfinder.com/support) page, section **FAQ**, question _GitFinder is running, but I don't see icon badges nor git menu commands?_ (second half of the answer). Pictures provided there refer to previous System Preferences (pre-Ventura), but the story is essentially the same. Use this "trick" if you encounter this issue again. And maybe one fine, bright day in the future, Apple will provide some better solution 🙂

**Comment by asegner** [comment]
Thanks for the summary - fingers crossed. 

> The trick here is to go over all FinderSync extensions in System Preferences and uncheck all, but the one you want to show its icon badges (GitFinder in this case). Once the desired extension takes over badge presentation, you can check back the others. 

This workaround does not appear to work for this particular pair of extensions. Well.... it kind of works initially, but it doesn't stick around after a reboot. I need the icon badges more than MacZip menu items, so i'll disable that extension for now until a better solution exists.

**Comment by milke** [comment]
It doesn't stuck after a reboot because, as I've said, the order in which OS starts extension is not deterministic 🙁

I really apologise and I hate it too, but there's nothing I can do about it. Now that you know the nature of the issue, perhaps you can file the same bug to Apple (if you have Apple developer account). The more people complain, the more willing they should be to tackle it, I guess.
