### ISSUE TITLE
GitFinderSync and GitFinder.GitService crashes with large repository folders

### ISSUE THREAD

**Issue by belazor** [milke/GitFinder-Issues#25]
Hi there,

I've encountered a few crashes with GitFinder, attached the .crash files.

[ag.zigz.GitFinder.GitService_2018-03-03-202531_Fillips-Mac-mini.txt](https://github.com/milke/GitFinder-Issues/files/1780591/ag.zigz.GitFinder.GitService_2018-03-03-202531_Fillips-Mac-mini.txt)

This crash has not been reproduced since, and may be related to the fact that I copied the repository folders from a Windows computer, before doing a clean `git checkout` of all repositories.

[GitFinderSync_2018-03-04-163939_Fillips-Mac-mini.txt](https://github.com/milke/GitFinder-Issues/files/1780593/GitFinderSync_2018-03-04-163939_Fillips-Mac-mini.txt)

[GitFinderSync_2018-03-05-111805_Fillips-Mac-mini.txt](https://github.com/milke/GitFinder-Issues/files/1780594/GitFinderSync_2018-03-05-111805_Fillips-Mac-mini.txt)

These crashes happen semi-randomly.

Do bear in mind that I have a very large Git folder; at the time of writing, it contains 138 repositories.

**Comment by milke** [comment]
Thanks for reports @belazor, I'll take a look at them.

**Comment by milke** [comment]
I haven't worked specifically on this, but version 1.2 introduces some major redesign of the way application and Finder extension work and interoperate. This should also contribute to increased stability and robustness of the combo and hopefully removes these crashes well.

I'll close this one, but if the issue reappears, please fill free to reopen (preferred), or create a new one.
