### ISSUE TITLE
No way to get back to Commit screen from View Changes screen

### ISSUE THREAD

**Issue by filliph** [milke/GitFinder-Issues#26]
If you click View Changes on commit, you get taken to this screen:

https://i.imgur.com/hOSDFfm.png

It is impossible to get back to the Commit screen without closing the window and restarting the commit process. This discards any commit message you were typing.

The View Changes screen should be shown as a separate window / overlay, not *instead of* the Commit screen.

**Comment by milke** [comment]
All action views are supposed to be modal and prevent further operations until the initialised action is finished or cancelled. Hence, they're presented as either modal windows (if started from Finder menus) or modal sheets (if started from repository browser window).

I realise this causes inconvenience with *Commit* action view you explained above. I'll think about how to redesign these action views to behave better (prevent further actual action on a repository, but enable "read-only" actions, like *diff*, *compare* and similar).

**Comment by milke** [comment]
Implemented in version **1.3**.
