### ISSUE TITLE
[Browser] Adding new lines to commit message uses unusual shortcut

### ISSUE THREAD

**Issue by belazor** [milke/GitFinder-Issues#30]
The enter key should insert a new line, and ⌘Enter should submit the commit.

Instead, I have to use ⌃Enter to add a new line, which is sub-optimal.

**Comment by milke** [comment]
Hm, I'm not sure about this one. At the moment, it follows the pattern of other text input fields (in GitFinder, but most other applications behave that way): hitting ENTER/RETURN sends the message to perform desired operation. If you really want a new line (`\n`) you have to press **alt/option** key when pressing ENTER/RETURN.

**Comment by AndrewLazarus** [comment]
I would prefer a preference to flop the use of plain Return and Option-Return.
