### ISSUE TITLE
Repeated dialogs stating "ag.zigz.GitFinder.GitService" quit unexpectedly

### ISSUE THREAD

**Issue by EricRFMA-ES** [milke/GitFinder-Issues#34]
Hello...
I just installed GitFinder on a Mac running Mac OS 10.11.6. Every couple of minutes or so, I see the following dialog pop up: 
![screen_capture_2018-04-24_at_2 18 54_pm](https://user-images.githubusercontent.com/10996566/39206187-b5bf1006-47ca-11e8-8b88-40d497b11f39.png)

I generally don't have any Finder windows with focus when this happens (it seems to be random)

The crashreporter log is here: 
[ag.zigz.GitFinder.GitService_2018-04-24-141919_Zarquon.txt](https://github.com/milke/GitFinder-Issues/files/1944069/ag.zigz.GitFinder.GitService_2018-04-24-141919_Zarquon.txt)

Hope this helps!

-Eric

**Comment by milke** [comment]
The good thing: it happens in GitService (it's an XPC service) so next time you need to execute some git operation from GitFinder, it will be regularly restarted.

The bad thing: for some reason, GitFinder (GitService XPC service, that is) chokes on creating a (Core Data backed) snapshot of the repository, so it can be quickly searched for commits, files, etc… Looking at the report I don't really see why that happens. Will you be willing to try some special debugging version, which would provide more debugging information in case it fails?

And one question: when this happens,  do you work with one or more git repos using GitFinder?

**Comment by EricRFMA-ES** [comment]
Sure, I’d run a debug version for you. And to answer your question, I think I was using multiple repositories at the time (I usually am).

Thanks!

-Eric

**Comment by milke** [comment]
I haven't worked specifically on this, but version 1.2 introduces some major redesign of the way application and Finder extension work and interoperate. This should also contribute to increased stability and robustness of the combo and hopefully removes crashes errors as well.

I'll close this one, but if the issue reappears, please fill free to reopen (preferred), or create a new one.
