### ISSUE TITLE
Spurious errors when using another Git client alongside GitFinder

### ISSUE THREAD

**Issue by uliwitness** [milke/GitFinder-Issues#37]
Hi,

often when I make changes using SourceTree (or SourceTree reloads its view), GitFinder throws up error dialogs about random files. It seems like SourceTree being busy with the repository prevents GitFinder from accessing it.

It would probably be helpful if GitFinder did one or two quiet re-tries to give SourceTree the opportunity to finish, and only if it persistently fails to do its thing, actually put up an error message.

Thanks!

**Comment by milke** [comment]
Can you tell me what specific error messages you get from GitFinder (perhaps a screenshot if error dialog)?

I don't use SourceTree (as a matter of fact, I use only GF for a bit longer than a year now), but I'd like to download it and reproduce this behaviour. The strange things is, if something else is modifying repo files monitored by GF, the only thing it needs is read access to update its status. It would be strange if SourceTree does something additionally while operating on files, like locking for read access or similar.

**Comment by uliwitness** [comment]
"failed to open directory '/Path/to/my/repo': Operation not permitted

**Comment by milke** [comment]
So far I haven't been able to reproduce this. Is there anything specific you do with repository in SourceTree when GF starts complaining?

**Comment by uliwitness** [comment]
It just happens when I push, or when I switch branches.

**Comment by milke** [comment]
I haven't working specifically on this, but version 1.2 introduces some major redesign of the way application and Finder extension work and interoperate. This should also contribute to increased stability and robustness of the combo and hopefully removes these errors as well.

I'll close this one, but if the issue reappears, please fill free to reopen (preferred), or create a new one.
