### ISSUE TITLE
Failed to create repository commits manager

### ISSUE THREAD

**Issue by scattersoft** [milke/GitFinder-Issues#42]
There was an error creating or loading repository commits database.

I just get this whenever I access any folder that is supposed to have a repo in it. Nothing works and I have to force quit.

**Comment by milke** [comment]
First of all, let's try to fix or find a workaround for the issue… GitFinder keeps its own database of cached repository commits and some other data for faster presentation and operations. That database is kept inside repository's (hidden) `.git` directory inside its own (also hidden) directory named `ag.zigz.GitFinder`, like in the picture below:

![Screen Shot 2019-03-20 at 19 24 08](https://user-images.githubusercontent.com/291305/54709426-c0253000-4b45-11e9-99ec-b6a5c4a84180.png)

Reveal hidden files in Finder (**cmd+shift+.** or you can execute all following operations in the terminal), go to directories of every affected repository, then go into their `.git` directory and delete `ag.zigz.GitFinder` directories from there. Check it this solves the problem.

It may happened GitFinder was repeatedly crashing for some reason and hence corrupted commits' databases. I'd appreciate if you open **Console.app**, select *User Reports* in the left sidebar and see if there are any crash reports coming from processes named **GitFinder** or **GitFinderSync**, or whose name starts with **ag.zigz.GitFinder**, like in the picture below:
![Screen Shot 2019-03-20 at 19 19 01](https://user-images.githubusercontent.com/291305/54709459-cddab580-4b45-11e9-8c54-76060b1d2adf.png)
Let me know if this helps.

**Comment by milke** [comment]
Closed due to inactivity.
