### ISSUE TITLE
Error: 'Repository is outside of "RepoFolders"' even though it is listed

### ISSUE THREAD

**Issue by ianthrive** [milke/GitFinder-Issues#45]
Opening a repository folder displays the error message 'Repsitory is outside of "Repo Folders"' even though the folder is listed.

The list of folders in Preferences > Repsitories cannot be changed. There are several folders listed, but attempting to add to or remove from the list has no effect.

**Comment by milke** [comment]
Hm, it seems for some reason one of the preferences file got corrupted. I'd like to know what happened, but I guess it's too late now. In any case I'll look in the code to see if I can identify situations when that may happen.

That being said, try the following procedure, it should fix things for you:
1. Make sure GitFinder is not running.
2. Delete preferences file: `~/Library/Containers/ag.zigz.GitFinder/Data/Library/Preferences/ag.zigz.GitFinder.plist`, or if you want to keep your settings, open that file and delete key `GFFoldersURLs`.
3. Delete preferences file: `~/Library/Group Containers/MQ76M469AB.ag.zigz.GitFinder/Library/Preferences/MQ76M469AB.ag.zigz.GitFinder.plist`, or again, to keep other preferences open that file and delete key `GFFoldersURLs`.
4. Open Terminal.app and execute this from there: "defaults read ag.zigz.GitFinder”.

After executing these steps, relaunch GitFinder, your repo folders list should be empty. Try to add a repository folder (or its parent) to “Repo Folder” preferences list. If it still doesn't work please let me know and we’ll see what further steps we can take to debug/resolve this issue.

**Comment by ianthrive** [comment]
Thanks, step 2 was all that was needed, I didn’t do anything else.

Here’s the .plist file in case it’s helpful.
