### ISSUE TITLE
GitFinder Errors when User Deletes Repo Synced to iCloud

### ISSUE THREAD

**Issue by luxlogica** [milke/GitFinder-Issues#46]
Newer versions of the MacOS allow the user to automatically keep their `~/documents` and `~/desktop` folders in iCloud. If the user has GitFinder watching repositories in one of these iCloud-synced folders, deleting the repository folder throws an error, every time:

<img width="461" alt="Screen Shot 2019-08-03 at 1 03 52 pm" src="https://user-images.githubusercontent.com/2994472/62406472-ce08b880-b5ef-11e9-859f-583538024cc6.png">

**Comment by milke** [comment]
OK, I can reproduce this. I'll investigate how to fix it. It certainly looks like sandbox annoyance.

**Comment by milke** [comment]
@luxlogica, I've just uploaded new beta version 1.3.1b2 (build 59), which fixes this issue. Please confirm it's fixed for you as well.

**Comment by luxlogica** [comment]
Thank you, @milke - it seems fine now (no more annoying message!). :)
