### ISSUE TITLE
GitFinder Quits When Replacing Just-Deleted Folder

### ISSUE THREAD

**Issue by luxlogica** [milke/GitFinder-Issues#48]
### Description
GitFinder unexpectedly quits when we replace a recently deleted repository folder with a copy (a folder with the same name and content).

### Steps to Reproduce
1. Download **[Kirby's Plainkit](https://github.com/getkirby/plainkit)** from their Github repository. You should end up with a folder called 'plainkit-master'. 
2. **Copy** the 'plainkit-master' folder into a location that is being watched by GitFinder
3. Using GitFinder, create a new repository on the 'plainkit-master' folder, and perform a couple of git operations - e.g., an initial commit, and a change to .gitignore.
4. Now, delete the 'plainkit-master' folder that GitFinder is tracking — put it in the trash/bin, and empty the trash/bin.
5. Finally, make a **new copy**  of the downloaded 'plainkit-master' folder, into the same location where the just deleted folder was. GitFinder will unexpectedly quit.

This is reproducible every time, with version 1.3.1b2.

**Comment by milke** [comment]
I believe I fixed this in the latest beta version **1.3.1b3 (build 60)**. You can update to it like you did before. I'd appreciate if you give this beta a try and confirm the issues are fixed. Thanks!

**Comment by luxlogica** [comment]
Thank you, @milke!
