### ISSUE TITLE
GitFinder Hangs if Branching on a Repository without Commits

### ISSUE THREAD

**Issue by luxlogica** [milke/GitFinder-Issues#50]
### Description
When we create a new repository, and before making an initial commit, if we try to create a new branch (from 'master') immediately, GitFinder hangs indefinitely with a 'Validating' window. We need to quit - or force-quit - GitFinder to exit it.

<img width="477" alt="Screen Shot 2019-08-17 at 12 42 27 pm" src="https://user-images.githubusercontent.com/2994472/63205790-fbc02800-c0ec-11e9-8428-7e81fc6268af.png">

### Steps to Reproduce
1. Create a new repository with GitFinder, using the 'Create...' menu command
2. Right after the repository is created, try to create a new branch from the default 'master' branch, by:
    a. selecting the 'Create a new branch from -> master' command in the contextual menu, OR
    b. opening the GitFinder Browser, control-clicking on the 'master' branch and selecting 'Create a new branch from master...'.

In both cases, we get a 'validating' window (or sheet), that never goes away, and never issues. an error. The only way to get out of it is to quit (or force-quit, in the case of 2.b) GitFinder.

**Comment by milke** [comment]
Okay, I've reproduced this. The point is, after creating a brand new repository and before any committing, the *"master/HEAD"* branch doesn't rally exist in the repository database, it's just a symbolic reference without a direct target. Some operations are not possible with such reference, hence shouldn't be allowed. This is how other git clients treat that reference as well.

The newest beta **1.3.1b4 (build 61)** fixes this. You'll notice when trying to perform some operations, they are disabled in action menus, or in some menus you'll see that *"master/HEAD"* branch present, but disabled, which should indicate it cannot participate in attempted operation.

Let me know if it all works as expected, or if you find some other issue.

**Comment by luxlogica** [comment]
Thank you for looking at this so quickly, @milke! Indeed, the user is no longer able to perform these operations on a new, empty repository anymore 👍 - awesome!

It's great that you disabled some of the menu commands, in some situations, until an initial commit is made. If I can only suggest one more thing, is that we should perhaps disable *a lot more*, in order to make the interface guide the user, allowing them to see at a glance what operations are available, and what isn't. For example, when the repository is brand new and without any commits - and only a single, 'master', local branch - control+clicking on the folder still gives us this (pretty full) contextual menu:

<img width="438" alt="Screen Shot 2019-08-20 at 9 56 21 am" src="https://user-images.githubusercontent.com/2994472/63307408-9dd05200-c331-11e9-97c9-d9c4fa531ab3.png">

While most of these commands cannot actually be selected at this point, they still 'look' available, and it would probably be more helpful to the user if they could be greyed out and unavailable - guiding the user to the operations that they _should_ be doing.

Similarly, if we go to the 'Browser' on the project, and control+click on the 'master' branch, we get this contextual menu:

<img width="423" alt="Screen Shot 2019-08-20 at 9 57 13 am" src="https://user-images.githubusercontent.com/2994472/63307478-df60fd00-c331-11e9-9358-c14e267cc679.png">

Because this is a brand-new, **local** repository only, with a single branch and no commits, none of those commands make sense (and perhaps the entire contextual menu could be disabled or unavailable).

Last of all, if we control+click on the 'Tags' section of the Browser, we can still select the 'Create Tag...' command:

<img width="335" alt="Screen Shot 2019-08-20 at 9 57 52 am" src="https://user-images.githubusercontent.com/2994472/63307563-2e0e9700-c332-11e9-9150-8755addb2b05.png">

Once selected, the tag creation sheet appears, with a warning message - it seems GitFinder is confused trying to find the commit it's supposed to be tagging:

<img width="462" alt="Screen Shot 2019-08-20 at 10 08 53 am" src="https://user-images.githubusercontent.com/2994472/63307727-c3119000-c332-11e9-87b0-70bf67eff0f1.png">

At this point, these are just suggestions to try and help improve the UI/UX, rather than correct any bugs, though - feel free to ignore them! 

Once again, thank you for being so responsive, and for putting together such an amazing piece of software.

**Comment by milke** [comment]
I'll consult Apple HIG (Human Interface Guidelines) regarding the best solution. I can't say from the top of my head, but I do remember there are cases in the guidance mentioning menu items, which should be present but disabled, as in "this action exists in general, but it's not executable for this particular item/case".

It's important the hang/crash doesn't happen any more, so I'm closing this and I'll open a new issue regarding better menu items availability logic.
