### ISSUE TITLE
up-to-date icon does not change after pulling upstream changes

### ISSUE THREAD

**Issue by azankl** [milke/GitFinder-Issues#59]
When I pull changes from an upstream repo, the status icon remains a green checkbox, even though my local repo now has changes that are not present in the origin repo. Is that a bug or meant to work this way?

**Comment by milke** [comment]
File icon badges in GitFinder show only the local status of files, that is the differences between working directory, repository index and repository HEAD. What each icon means can you see on the [**support**](https://gitfinder.com/support) page, section **FAQ**, subsection "**What does each GitFinder icon badge mean?**".

Icon badges don't show differences between local and remote version of a file. And currently I don't really have any idea how to visually indicate that, but I'm open to hear them.

**Comment by azankl** [comment]
Ok, can't think of a good way either, will let you know if I come up with something.
