### ISSUE TITLE
"config value 'remote.origin.skipfetchall' was not found" when opening GitFinder

### ISSUE THREAD

**Issue by ddobrev** [milke/GitFinder-Issues#63]
When any window of Finder is already open, and I activate GitFinder, I get 3 consecutive warnings: "config value 'remote.origin.skipfetchall' was not found" and then "Operation not permitted" twice. And then GitFinder doesn't work i.e. doesn't show its menus in the repository. I have to close all windows of Finder and then activate GitFinder for it to work.
The same happens upon starting the OS up, presumably because it usually starts with an open window of Finder.

**Comment by ddobrev** [comment]
Hello, could you reply, please? I'm afraid this bug makes the product almost useless.

**Comment by milke** [comment]
@ddobrev, the thing is, I've been trying to reproduce this error, but I just can't and nobody has reported anything similar in the past. Also, having or not Finder windows open when launching GitFinder should have no effects on behaviour at all, so this all makes it even more strange. The errors reported could be more related to some kind of sandboxing issue, regardless of the  Finder windows opened. A few questions:

**1.** Do you get this error only when there are already Finder windows open showing any particular repository, or any Finder window (e.g. showing your */Applications* folder) is enough to generate the error?

**2.** If (1) is only when Finder shows some repository, does that happen with every repository you try, or only some of them?

**3.** If (2) is only on some repositories, would it be possible to get a copy of any such repository causing the problem?

**Comment by ddobrev** [comment]
1. Just checked now to make sure, I think it's when showing a repository;
2. So far I only use GitFinder with one repository;
3. Of course, it's https://github.com/mono/CppSharp.

**Comment by ddobrev** [comment]
I really hope you can quickly fix this. In other instances it shows no messages but simply refuses to load its context menu, regardless of Finder windows.
I was forced to install SourceTree today which I consider as a concept a much inferior client but I was simply unable to do my job with GitFinder.

**Comment by ddobrev** [comment]
@milke are my answers enough for you to proceed?

**Comment by milke** [comment]
@ddobrev, I've managed to reproduce this and since it's not very deterministic, I can't be completely sure, but I think I fixed it (it was related to the changes in the latest versions of libgit2 library, which I haven't handled correctly). The fix is available in the new beta version **1.5.3b1**, which I've just released. You can automatically update to it by checking for updates from the update preferences (select the **Beta** release channel). There are some other semi-related small fixes, you can check them the release notes while updating.

Please update to this beta and give it a try for a week or so. If it works fine, you don't have to react and I'll assume it's fixed. However, if you encounter the problem again, report it back, so that I can look further.

**Comment by ddobrev** [comment]
Thank you for your effort. It works after about 5 or 6 attempts. But as you suggest, I'll make sure to report again should it reoccur.

**Comment by ddobrev** [comment]
I haven't seen the message any more but the overlays and menus disappeared and I cannot get them back no matter how many times I restart GitFinder and whether the folder is already open or not.
Is degraded performance for reasons similar to https://github.com/milke/GitFinder-Issues/issues/64#issuecomment-714757406 a possible culprit?

**Comment by ddobrev** [comment]
I had 4 dangling processes called "GitFinderSync". I killed them all and then started GitFinder — to no avail. Another strange behaviour is that even when GitFinder is off, I can see an overlay of my root folder and the additional non-context menu which stays empty.

**Comment by ddobrev** [comment]
I'm sorry to say this latter problem's forced me to reinstall Sourcetree. It happened for a second day in a row and so far when it does, it cannot be fixed (short of restarting the machine). As you understand, this problem too makes GitFinder useless so any help you think I can give you, you've got it. For example, if you feel this is a different problem, I can report a new bug for you.

**Comment by ddobrev** [comment]
I think I'm starting to detect a pattern. It happens regularly after staying on for a long time i.e. throughout the workday. It might be related to the sleep and resume cycles. Each time it occurs there's more than one GitFinderSync process which suggests this process isn't only started when the OS turns on but when it resumes from hibernation as well.

**Comment by milke** [comment]
I've just uploaded new beta **1.5.3b2 (build 83)**, you can update to it the same way as before. It combines both improvement in directory traversal in case of ignored files, as well as these potential problems with Finder Sync process going out of sync (and hence not showing icons and menu commands). Try it out and let me know if you still experience problems. Like said in #64, there is room for improvements as well, I'm just interested if I'm on the right path.

**Comment by ddobrev** [comment]
I've already installed it to test the other problem. This particular issue I cannot immediately reproduce but I'll let you know if it still happens.

**Comment by milke** [comment]
As of **GitFinderSync** processes and many of them running… Those Finder Sync processes are controlled (launched/killed) by the OS (Finder actually), and the OS can arbitrarily run many of them if found necessary, for whatever reason. I know it's strange but that's how it is and I decided not to try to control their launch and termination. That's also the suggestion of Apple documentation.

Before macOS 10.15 Catalina, I was actually controlling them completely. On launch, the application would check if there were any "loose" sync process running and if so, kill it before finishing launching. Also, upon finishing launching, the application would make sure the new sync process is started. And on application termination, it made sure all running sync processes are terminated as well.

Unfortunately, some things regarding this control broke with Catalina and not only that it'd be so hard to achieve it back without a lot of dirty hacking, but I also realised it would probably brake with each major (and sometimes even minor) OS update. Hence I decided to follow the docs and left those processes alone, instead focusing to assure proper synchronisation and messaging between the application and running sync processes, especially when it comes to cleaning up when one party terminates.

It still may not be perfect, but I'm improving it every time someone report problems, like you now.

**Comment by milke** [comment]
> I've already installed it to test the other problem. This particular issue I cannot immediately reproduce but I'll let you know if it still happens.

Give it a week or so and let me know if it starts behaving again.

**Comment by ddobrev** [comment]
Thank you for the explanation, I might find it useful one day. It seems to me the behaviour of the OS was better before but I hope it won't obstruct GitFinder.
I've configured it to launch after logging in so in a way I now use it every day. If the problem persists, I'll see it again soon enough.

**Comment by milke** [comment]
Just a short update, I've just uploaded new beta **1.5.3b3 (build 84)**, you can update to it the same way as before. It works as before, I just took this opportunity of fixing/improving things you reported to implement some further fixes and implementations, which waited for quite awhile on my list, but never made it to the top (you can read details in the update release notes). Just use it as you regularly do and let me know if anything goes wrong. If not, I'll probably release it as the official one beginning next week.

Thanks for your time, testing and reporting 👍

**Comment by ddobrev** [comment]
And thank you for making one of my professional dreams come true. 👍
