### ISSUE TITLE
Pulling stuck at validating

### ISSUE THREAD

**Issue by ddobrev** [milke/GitFinder-Issues#67]
I amended and force pushed a branch from another location. In order to get the changes with no conflicts, I reset the copy I use on macOS to an older commit and then pulled. It's been stuck at "Validating" for at least 10 minutes now. I can neither close the window nor pull again since all operations are disabled. I'm forced to kill GitFinder to try again.

**Comment by milke** [comment]
@ddobrev, please take a look at my first comment in #71. Is that your case as well (_"hooks"_ spinning gear in the main menu while being stuck at _"validating"_)?

**Comment by ddobrev** [comment]
I haven't noticed but I'm definitely going to inform you if I see anything similar.

**Comment by milke** [comment]
If you get stuck while pulling… Pulling can invoke execution of a couple of git hooks, if they're present in `reporoot/.git/hooks/`. If there's anything to really pull (the reference pulled into is behind the reference being pulled, or most commonly, local branch is behind its tracking remote branch), `post-merge` hook will be executed (if present), even if pulling merge is fast-forward (without an actual merge commit being made). Additionally, if pulling merge isn't fast-forward so the actual merge commit is created, `pre-commit`, `post-commit` and `commit-msg` hooks will be executed (if present). Do you have any of these hooks in your repository? If so, then you can confirm their execution is the culprit if next time when you get stuck while pulling, you see that _"hooks"_ spinning gear from #71.

But if you don't have any of those hooks and you get stuck, then the whole story above is pointless and the problems is something else.

**Comment by ddobrev** [comment]
I have no hooks in my repo, it's the same I sent you before.

**Comment by milke** [comment]
> I have no hooks in my repo, it's the same I sent you before.

It's something else then… I'd appreciate if the next time it happens and while being stuck, you open **Activity Monitor.app**, find **GitFinder**, **ag.zigz.GitFinder.GitService** and **ag.zigz.GitFinder.KeychainService** processes and take samples of them all. Also observe eventual increased CPU usage of the latter two ones.

**Comment by ddobrev** [comment]
I've [uploaded some crash reports](https://github.com/milke/GitFinder-Issues/files/5549909/Archiv.zip), they might help you here.

**Comment by milke** [comment]
> I've uploaded some crash reports, they might help you here.

Thanks, but in this case I'd really appreciate process samples while GitFinder is being stuck in validating while pulling. Thanks 👍

**Comment by milke** [comment]
Closing this due lack of activity and it it should be fixed anyway. @ddobrev, if you encounter similar problems with the latest release of GitFinder, please let me know and reopen the issue.
