### ISSUE TITLE
GitFinder's menus and commands (context menu) disappear

### ISSUE THREAD

**Issue by ddobrev** [milke/GitFinder-Issues#68]
I have mentioned this at https://github.com/milke/GitFinder-Issues/issues/63#issuecomment-715624427. I cannot reproduce how it happens, this time the computer didn't even sleep and all menus were gone within 30 minutes. What makes this horrible is that when it happens, nothing helps restore the functionality. No amount of quitting or killing processes of GitFinder and GitFinderSync helps. I would guess I'd have to restart or at least log out and back in. This essentially means that one must always have a spare Git client in case GitFinder breaks – which makes the latter unreliable.

**Comment by milke** [comment]
I'm really struggling to figure out what's going on there on your end. The only reason I could see for icon badges and contextual menu commands to disappear is GitFinderSync crashing. But then again, killing all related processes and launching GitFinder again should put all back in order. Two questions:

**1.** Do you see any crash report coming from **GitFinderSync** that happened recently? You can find them either in the _"Crash Reports"_ section of the **Console.app** or in `~/Library/Logs/DiagnosticReports/`.

**2.** In case you still use GitFinder and that happens again, don't kill anything, don't even quit **GitFinder** application, just kick off the terminal and execute there the following: `killall Finder`. Does that put things back in order (after Finder is restarted)? Also immediately after that, check crash reports and see if there is a fresh one coming from **GitFinderSync**.

**Comment by ddobrev** [comment]
[Archiv.zip](https://github.com/milke/GitFinder-Issues/files/5549909/Archiv.zip)
@milke these are all reports on my machine at present. I hope they're useful.
Thank you for the tip. It hasn't happened for almost 2 weeks now but if it does, it might come in handy.

**Comment by milke** [comment]
Thanks 👍  No crashes of GitFinderSync though?

**Comment by ddobrev** [comment]
I'm sorry the reports aren't as useful as I'd hoped but they're all I have.

**Comment by milke** [comment]
Ah, don't misunderstand it… Crash reports are always useful and I'll investigate why GitService crashed on you a couple of times. It's just that, due to the nature of the issue, I expected some GitFinderSync crashes there as well.

**Comment by flipphillips** [comment]
I have the exact same scenario — something not-uncommon for me, it seems. I lose the 'badging' for Google Drive sometimes, as well as other Finder extensions, so I wonder if it's a more systemic thing at work? 

The limit of what I see in my logs, right now, are

```
Dec  8 00:51:20 gan-fxpppr-m com.apple.xpc.launchd[1]: Coalition Cache Evicted: app<application.ag.zigz.GitFinder.12925560.12925565(1240675623)> [834]
Dec  8 15:17:49 gan-fxpppr-m com.apple.xpc.launchd[1]: Coalition Cache Evicted: app<application.ag.zigz.GitFinder.12925560.12925565(1240675623)> [853]
Dec  8 16:49:59 gan-fxpppr-m com.apple.xpc.launchd[1] (ag.zigz.GitFinder.GitFinderSync.9B2E8193-8DF4-4FF9-B5A2-D7B7D8F55143[68959]): Service exited due to SIGKILL | sent by GitFinderSync[68959]
Dec  8 16:49:59 gan-fxpppr-m com.apple.xpc.launchd[1] (ag.zigz.GitFinder.GitFinderSync.CCF4DE1A-5B08-48D0-B66A-BB7672B4794D[919]): Service exited due to SIGKILL | sent by GitFinderSync[919]
Dec  8 16:50:04 gan-fxpppr-m com.apple.xpc.launchd[1] (ag.zigz.GitFinder.GitFinderSync.3D156F13-7AB3-4C8F-9F4D-5A920AD0067C[68319]): Service did not exit 5 seconds after SIGTERM. Sending SIGKILL.
Dec  8 16:50:04 gan-fxpppr-m com.apple.xpc.launchd[1] (ag.zigz.GitFinder.GitFinderSync.53C781DD-0C44-497F-AB53-3AAEF1E9A580[68240]): Service did not exit 5 seconds after SIGTERM. Sending SIGKILL.
```

I'm happy to help debug this as well...

**Comment by milke** [comment]
Closing this due lack of activity. @ddobrev and @flipphillips, if you encounter similar problems with the latest release of GitFinder, please let me know and reopen the issue.
