### ISSUE TITLE
[Bug] GitFinder Inappropriately Warns When Project Folder Is Moved

### ISSUE THREAD

**Issue by luxlogica** [milke/GitFinder-Issues#70]
I was doing some house cleaning - i.e., archiving some old projects, and deleting some others - and came across an 'unwanted feature' of GitFinder: it seems GitFinder keeps track of its previously-tracked repository folders, even after they've been moved out of the 'Repo Folder' directories - and helpfully suggests that we should add the new locations to the 'Repo Folders' preference:

<img width="279" alt="Screen Shot 2020-11-14 at 11 18 16 am" src="https://user-images.githubusercontent.com/2994472/99132899-107ec900-266c-11eb-893c-4b515f4c59f8.png">

While I can see how helpful GitFinder is trying to be, there are many situations in which this is not only NOT very helpful, but downright inappropriate - like the example above (it should not be suggesting I add the 'Trash' folder to the Repo Folders...).

Also, it keeps on tracking the moved project folders BETWEEN RELAUNCHES: I quit GitFinder, and when I re-launched it, it "helpfully" asked me again about all the projects I had moved (or deleted). All 20+ of them...

Honestly, I don't see that as a very necessary feature. We have to manually setup the watched Repo Folders, so we are very aware that taking a project folder out of it means GitFinder will no longer be actively 'tracking' it - and that is normally the behaviour we want.

In order for this feature to be truly helpful, there are several checks that would have to be put into place, such as:
- location checks, so that GitFinder doesn't naïvely suggest users put 'Trash', 'Library', 'System', and other folders under tracking, which could cause several issues. Note that this would have to include also folders that are tracked by other cloud-based backup systems, like iCloud, DropBox, GoogleDrive, etc.
- GitFinder would also need to keep track of all the projects/folders that the user has already clicked 'Cancel' about, so they don't keep getting the same warning, over and over, every time GitFinder launches. 

But IMHO, GitFinder here is trying to do too much, and it would be simpler for all if GitFinder simply not did this check at all, and just allowed users to move - and delete - their project folders without nagging.

**Comment by milke** [comment]
It's nice that you think GitFinder is trying hard to be "smart" and keeps track of open repositories, even BETWEEN RELAUNCHES, and then tries to open them back, even if they're moved outside of the _"Repo Folders"_, or even trashed. But what happens is actually a (sort of) bug and it's a consequence of the quite complicated relationship between GitFinder application and it's accompanying Finder Sync extension (GitFinderSync). It'd all be nice and fine if the application could just launch the extension on its own launch and also kill all extension processes (there may be more of them, started by the OS/Finder) on its own termination. And it used to work that way, but then it got broken on Catalina, so I decided to listen to Apple docs and DO NOT try to control sync extension processes life span; their launch and termination should be left to the OS and I just have to make sure they synchronise correctly on application launch and termination. And it's not very easy, there are a lot of things that can happen with the extension while the application isn't running and once it's launches it has to catch up with all the events that happened to the extension(s) in the meanwhile.

I can make this story a lot longer and try to explain what really happens (and why this but is not always reproducible, even after repeating exactly the same steps), but I don't think it's necessary. Let me just say that in a couple of days I'll upload **1.6.1 beta**, which will hopefully fix this behaviour. And hopefully that fix will also fix issues in #60 as well.

I'll let you know here once this beta is available.

**Comment by milke** [comment]
I've just uploaded **1.6.1b1** and it should fix this error (actually the appearance of the error :-)). Check it out and let me know if you still see it.

**Comment by milke** [comment]
Okay, I consider this fixed (the fix is now in the official release **1.6.1**), so I'm closing this. If the issue reappears, feel free to reopen.
