### ISSUE TITLE
[Bug] Browser Shows a Change, But Unable to List Changed File

### ISSUE THREAD

**Issue by luxlogica** [milke/GitFinder-Issues#72]
On MacOS Big Sur 11.0.1, GitFinder 1.6. I open the GitFinder browser on one of my repositories, and it tells me that in my Working Copy there is **1 modification**. But clicking on 'Working Copy' shows...nothing!

<img width="1017" alt="Screen Shot 2020-11-14 at 10 55 35 am" src="https://user-images.githubusercontent.com/2994472/99134073-871dc580-2670-11eb-8ce0-780ea75dcb03.png">

A little investigation shows that the file GitFinder has detected as new/changed is a .gitattributes file:

<img width="204" alt="Screen Shot 2020-11-14 at 11 53 32 am" src="https://user-images.githubusercontent.com/2994472/99134117-ac123880-2670-11eb-8ac7-0df3605cd2ac.png">

I have not added that file there myself, so I'm guessing GitFinder must have created it itself as I changed some setting in the project - e.g., git-lfs settings, perhaps? In any case, it doesn't list the file in the browser, and therefore makes it difficult for me to track the file and commit it. 

Unfortunately, this is not consistent: I have noticed this happening with 2 repositories, while with others I can see the .gitattributes files in the GitFinder browser without any problems.

**Comment by milke** [comment]
I've just uploaded **1.6.1b1** and that version should fix this issue. Try it out and let me know if you experience this issue again.

**Comment by milke** [comment]
Okay, I consider this fixed (the fix is now in the official release **1.6.1**), so I'm closing this. If the issue reappears, feel free to reopen.
