### ISSUE TITLE
App fail after install, no git functions

### ISSUE THREAD

**Issue by AddictArts** [milke/GitFinder-Issues#75]
It fails, no icons and context menu. Just shows this warning. 

`Global git configuration file includes other configuration file at path "/etc/gitconfig" which is not selected in "Includes" configuration. Select in "Includes" configuration included file at path "/etc/gitconfig".`

My gitconfig does not reference any other files.

I also cannot select my .gitconfig in the GIt Configuration. ~/.gitconfig is grey.

**Comment by AddictArts** [comment]
PS: When includes pops up there is nothing to select. And quit kills GitFinder.

**Comment by milke** [comment]
@AddictArts, sorry about the delayed response, I was busy with other things (some of which were related to GitFinder, come not).

For start, before stating to look into this, just to confirm that there actually is file at path `/etc/gitconfig` in your filesystem, containing some git configuration, right?

**Comment by AddictArts** [comment]
Yes there is.

**Comment by milke** [comment]
@AddictArts, please update your copy to the latest beta, that I've just released, version **1.6.2b3**. You can upgrade your copy automatically, just choose **Beta** release channel:
<img width="448" alt="Screen Shot 2021-02-16 at 23 39 21" src="https://user-images.githubusercontent.com/291305/108131367-733f9080-70b1-11eb-9841-632dfd0dea30.png">
Or you can download it directly [**here**](https://get.gitfinder.com/GitFinder_beta.dmg). Let me know if that version solves this particular problem.

**Comment by milke** [comment]
@AddictArts, any luck with beta version **1.6.2b3**?

**Comment by milke** [comment]
I'm closing this now, as changes implemented in **1.6.2** fixed (hopefully) this issue. @AddictArts, if you still have this problem, please reopen the issue.
