### ISSUE TITLE
App requires access to home directory to function, no directory icons either, and gitfindersync is running

### ISSUE THREAD

**Issue by AddictArts** [milke/GitFinder-Issues#76]
After install the app would not see a directory as a git repo, no context menu. Then I add the home directory to repositories and it works. This is not intuitive and should be handled in a different way if it needs ~/.gitconfig for example.

No directory icons, gitfindersync is running. Control Panel extensions GitFinder is enabled in all the spots.

This issue is another Mac with Catalina, not completely related to the includes weird issue I filed #75.

These issues on new Mac installs make it a frustrating experience.

**Comment by milke** [comment]
I'm closing this now, as changes implemented in **1.6.2** and !!1.7** fixed (hopefully) this issue. @AddictArts, if you still have this problem, please reopen the issue.
