### ISSUE TITLE
Missing label in git config dialog

### ISSUE THREAD

**Issue by unikitty37** [milke/GitFinder-Issues#78]
I'm assuming you didn't mean to call it `XDG_CONFIG_HOME`, anyway :)

![image](https://user-images.githubusercontent.com/139183/127121220-5500386b-b1cb-4eec-a7a7-5fa6336c136f.png)

v1.7.1 (104)
macOS 10.14.6 (18G9216)

**Comment by milke** [comment]
Actually, it says exactly what it should. [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines a bunch of environment variables, one of which is `$XDG_CONFIG_HOME`, which is used by git. The specification describes it as:

> `$XDG_CONFIG_HOME` defines the base directory relative to which user-specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.

If you have any suggestion about what the UI should state instead, I'd like to hear it, although I think it'd only create bigger confusion.

**Comment by unikitty37** [comment]
Ah, I wasn't parsing it as a shell variable. Perhaps adding the leading `$` would help?

**Comment by milke** [comment]
> Perhaps adding the leading $ would help?

Yeah, that makes sense. Will do.

**Comment by milke** [comment]
Just a note, regularly setting this variable in GitFinder to match the one you set already (in case it defers from the specified default) shouldn't be necessary, it should work out of the box. But GitFinder is fully sandboxed application, so if the variable doesn't have a default value (`$HOME/.config`), one need to specify it manually, so it can be included into GitFinder's sandbox.

**Comment by milke** [comment]
_'$'_ added in new beta version **1.7.2b1 (build 105)**. You can download the new beta [**here**](https://get.gitfinder.com/GitFinder_beta.dmg), but you can also upgrade your current copy automatically, just select **Beta** release channel.

**Comment by milke** [comment]
This is now officially available in version **1.7.2 (build 108)**, so I'm closing this.
