### ISSUE TITLE
Keyboard shortcuts menu is empty

### ISSUE THREAD

**Issue by unikitty37** [milke/GitFinder-Issues#81]
The help icon implies that there should be a list of menu items displayed here — there certainly isn't an Add button or anything like that…

![image](https://user-images.githubusercontent.com/139183/127127318-ff60d8fe-da0d-4513-9c83-d6a4c0691ae0.png)

v 1.7.1 (104)
macOS 10.14.6 (18G9216)

**Comment by milke** [comment]
Hm, that's strange… Can you reliably reproduce it? You should see something like this in that view:
<img width="495" alt="Screen Shot 2021-07-27 at 11 33 43" src="https://user-images.githubusercontent.com/291305/127131868-2d67a95c-eb90-449f-b6e1-64774db873d1.png">

**Comment by unikitty37** [comment]
I've tried quitting and restarting; I've tried uninstalling and reinstalling. Neither seems to make a difference.

I can't find any entries in Console.app referencing GitFinder.

**Comment by milke** [comment]
Okay, I'll try to figure out what's happening there… You're on Catalina, right?

**Comment by unikitty37** [comment]
Mojave — can't go past that on this Mac Pro (thanks, Apple!)

**Comment by milke** [comment]
Okay, went back to Mojave and I can see it. Going to see why that happens…

**Comment by milke** [comment]
Okay, I believe new beta version **1.7.2b1 (build 105)** fixes this. And it wasn't related to Mojave only. Please try it out and let me know if you still can reproduce it. You can download the new beta [**here**](https://get.gitfinder.com/GitFinder_beta.dmg), but you can also upgrade your current copy automatically, just select **Beta** release channel.

**Comment by unikitty37** [comment]
That's working as expected — thanks!

**Comment by milke** [comment]
The fix is now officially available in version **1.7.2 (build 108)**, so I'm closing this.
