### ISSUE TITLE
Can't add private key file for SSH connection

### ISSUE THREAD

**Issue by yig** [milke/GitFinder-Issues#84]
I am trying to use GitFinder to interact with a remote repository on GitHub via the ssh protocol. GitFinder asks me to "Choose private key file for SSH connection with repository at...". When I choose a private key in my `~/.ssh/` folder, I get an error: "Invalid Private Key File: invalid format".

**Comment by milke** [comment]
What is the format of that SSH key? ed25519, rsa, dsa, ecdsa…?

**Comment by yig** [comment]
It doesn't like any of my keys generated with `ssh-keygen`.
One of them I generated with this command: `ssh-keygen -f id_rsa -t rsa -C 'name@domain.com'`
I didn't save the commands that generated the others I tried. I was probably following this article: https://security.stackexchange.com/questions/143442/what-are-ssh-keygen-best-practices

**Comment by milke** [comment]
@yig, I've just tried to authenticate with a new key, which I created with exactly the same command you posted here:
```
ssh-keygen -f id_rsa -t rsa -C 'name@domain.com'
```
I only used different comment/email address. And everything worked without a problem. Hence, I'd like to ask you for a favour: would it be possible to get any of those keys, causing problems to you? For example, exactly that one you created with the above mentioned command. Or if you are already using it elsewhere, can you create a new one, confirm that it causes "Invalid Private Key File: invalid format" error and then send it to me so I can test it out?

Thanks in advance.

**Comment by yig** [comment]
This is the issue: https://serverfault.com/questions/854208/ssh-suddenly-returning-invalid-format/1025451#1025451

It looks like the key format changed between when I last generated my keys and now. I was able to convert my GitHub key with the linked answer: `ssh-keygen -f ~/.ssh/id_rsa -p`

**Comment by milke** [comment]
Okay, but just for clarification, your converted keys work okay with GitFinder now?

**Comment by yig** [comment]
Correct. My converted keys work with GitFinder.

**Comment by milke** [comment]
Okay, I'm closing this one now, glad it all worked fine at the end :-)
