### ISSUE TITLE
Repository on iCloud drive

### ISSUE THREAD

**Issue by vr8hub** [milke/GitFinder-Issues#87]
In trying out GitFinder, I added a parent directory on the main hard drive that has a number of repositories in it, and everything worked great—the parent directory shows the GitFinder symbol, and all of the repositories show as well.

I then added a single repository directory that resides on my iCloud drive, and it's not working. No GitFinder icon, either on the directory or any of the files. I tried quitting GitFinder and re-starting it, but no change.

Is that a known limitation, or is there something I haven't done that needs to be done?

**Comment by milke** [comment]
> Is that a known limitation?

Unfortunately, yes :-(
You can also read about it [**here**](https://gitfinder.com/support), **FAQ** section, question _"GitFinder is running, but I don't see icon badges nor git menu commands?"_, last paragraph. Some system folders cannot be monitored by Finder extensions. Such folders are, for example, `iCloud Drive`, `/System` and `/Library`. It's just a limitation of FinderSync API and no workaround is possible.

I've filed a but report on unsupported `iCloud Drive` a long time ago, but that didn't bring any positive change.

**Comment by vr8hub** [comment]
Bummer. That's a deal-killer, unfortunately. The last line of that FAQ might apply to /System and /Library, but it definitely doesn't to the iCloud drive. It's the quickest and easiest way to edit a local repository across multiple Macs. Been doing it for ages.

You might consider promoting "Can GitFinder work on a repository on my iCloud drive?" to a top-level FAQ. I never would have thought to look for the answer buried in that particular FAQ, since GF _was_ working elsewhere.

**Comment by milke** [comment]
> Bummer. That's a deal-killer, unfortunately. The last line of that FAQ might apply to /System and /Library, but it definitely doesn't to the iCloud drive. It's the quickest and easiest way to edit a local repository across multiple Macs. Been doing it for ages.

I haven't tried it, hence I don't know if it would work, but you can try sharing your `~/Desktop` and/or `~/Documents` folders in iCloud Drive settings, they should still be monitored by GitFinder and shared across multiple Macs (I believe). Apart from that, nothing more that I can really do about it :-(

Maybe you can file a bug report for the same reason. Perhaps if more people do it, Apple may consider changing it.

**Comment by vr8hub** [comment]
I don't want my Desktop and definitely Documents to be in iCloud. I completely understand, you're at the mercy of what Apple allows. It just doesn't work for my use case. :(

**Comment by milke** [comment]
No problem, I was just throwing some ideas out. I don't want my `~/Desktop` and/or `~/Documents` in iCloud either.

So, I'm closing this one. Who know, maybe Apple changes its/their mind.
