### ISSUE TITLE
image distorted in "Git Configuration > Identities"

### ISSUE THREAD

**Issue by dvhwgumby** [milke/GitFinder-Issues#89]
See Screen shot: my icon should appear as a circle, not oval.
<img width="368" alt="Screen Shot 2021-07-29 at 08 10 06" src="https://user-images.githubusercontent.com/450612/127522087-dba46d32-bcc6-4a86-b5a4-29870ffab54d.png">

**Comment by milke** [comment]
Yeah, recently have I changed the routine to clip images to a circle, and I screwed it up. It happens if a source image isn't a perfect square. I'll fix it in the next update.

**Comment by milke** [comment]
The fix is now officially available in version **1.7.2 (build 108)**, so I'm closing this.
