### ISSUE TITLE
How do I format a commit message properly?

### ISSUE THREAD

**Issue by michaelgwelch** [milke/GitFinder-Issues#91]
I'm using version 1.7.2 (108). I was using the browser to stage some changes and commit.

The text box for the commit message doesn't appear to accept newlines. So I assumed that it would automatically wrap to 70 characters. But it doesn't do that, and even if it did, I might want to add newlines to start a new paragraph.

For now, the commit message text box doesn't seem usable for anything but short commit messages that are already less than 70 chars long.

**Comment by milke** [comment]
It actually accepts newlines, to save myself from typing please see #30.

Anyway, I do agree that maybe some indicator for the (unofficial) standard 70 characters per line should exist. I'm reluctant to wrap lines automatically, as that may not be what everyone wants, but I can add an indicator of a current line length, just like there's one in the **Subject** field.

**Comment by michaelgwelch** [comment]
Agreed, that auto-wrapping would not be a good idea. I only considered that might be what was going on because I couldn't figure out how to enter a newline.
