### ISSUE TITLE
Animoji avatar display is broken, no way to change

### ISSUE THREAD

**Issue by adrianhaus** [milke/GitFinder-Issues#93]
My Animoji contact picture (don’t judge) which automatically gets used as the avatar for me git identity is weirdly shifted down:
<img width="175" alt="Screen Shot Animoji" src="https://user-images.githubusercontent.com/10817640/128176283-8092a723-7ffd-4e2a-b7fd-1b57e969b21e.png">
It looks like that everywhere in GitFinder, but in other apps it’s fine.

The ability to customize (or hide) the avatars would also be a nice.

I’m running Big Sur 11.2.3 on an Intel MacBook Pro.

**Comment by milke** [comment]
GitFinder tries to make round images of user avatars. It usually works fine if the original image is a square (thus, of the same sizes horizontally and vertically). If the original image is a general rectangle, it's firstly cropped into a square preferring the smaller size, and then rounded. Could you export your Animoji picture and post it here, so that I can investigate what went wrong in this particular case?

**Comment by adrianhaus** [comment]
Ah, so apparently [the Animoji user pictures are tall rectangles](https://user-images.githubusercontent.com/10817640/128316503-f6565d0d-7142-4729-a0c4-478fcbb511f7.png) (561 × 1024) with the Animoji in the middle. So the cropping should center the image instead of taking the bottom part (which sounds like a reasonable way to do it in general).

**Comment by milke** [comment]
Okay, cropping the centre of the image is probably more logical, as the _"most important part of the image"_ is probably in the centre. So, that modification/fix is available in the new beta, version **1.7.3.b1 (build 109)**, so try it out. You can download it [**here**](https://get.gitfinder.com/GitFinder_beta.dmg), but you can also update your current copy to it, just choose **Beta** release channel in **GitFinder > Preferences > Updates**.
<img width="495" alt="prefs" src="https://user-images.githubusercontent.com/291305/128428508-433e9f0a-4809-4461-a482-61229e3216cf.png">
Let me know if it's okay now.

**Comment by adrianhaus** [comment]
Thanks, it’s fixed now!
